[project]
name = "timebermanageapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Quetin Descombes", email = "quentindescombes2004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
timebermanageapi = "timebermanageapi:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
